FROM python:3.13-slim

WORKDIR /app

# IMPORTANT: fix SSL + pip reliability inside slim images
RUN apt-get update && apt-get install -y \
    ca-certificates \
    && update-ca-certificates

RUN python -m pip install --upgrade pip setuptools wheel

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]